using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CS2Path.Core;

namespace CS2Path.Harness
{
    /// <summary>
    /// Standalone harness (plan §5): `verify` asserts algorithmic correctness
    /// against reference Dijkstra; `bench` measures Layer 0-3 costs against the
    /// §6 acceptance targets at 10^5-node scale; `herding` runs the
    /// synchronized-demand A/B; `sim` runs the full integrated simulation at
    /// 100k trips; `all` runs everything and writes RESULTS.md.
    /// </summary>
    public static class Program
    {
        public static int Main(string[] args)
        {
            string cmd = args.Length > 0 ? args[0] : "all";
            var opts = ParseOpts(args);
            ulong seed = (ulong)GetOpt(opts, "seed", 20260804);
            switch (cmd)
            {
                case "verify":
                    return TestRunner.RunAll(seed, out _);
                case "bench":
                {
                    var md = Bench(opts, seed);
                    File.WriteAllText("results-bench.md", md);
                    Console.WriteLine("\nwrote results-bench.md");
                    return 0;
                }
                case "herding":
                {
                    var md = Herding.RunAB(out _);
                    File.WriteAllText("results-herding.md", md);
                    Console.WriteLine("\nwrote results-herding.md");
                    return 0;
                }
                case "sim":
                {
                    var md = SimAtScale(opts, seed);
                    File.WriteAllText("results-sim.md", md);
                    Console.WriteLine("\nwrote results-sim.md");
                    return 0;
                }
                case "all":
                {
                    var sb = new StringBuilder(Header());
                    int rc = TestRunner.RunAll(seed, out var verifyReport);
                    sb.AppendLine("## Correctness verification");
                    sb.AppendLine();
                    sb.AppendLine("```");
                    sb.Append(verifyReport);
                    sb.AppendLine("```");
                    sb.AppendLine();
                    sb.Append(Bench(opts, seed));
                    sb.AppendLine();
                    sb.Append(Herding.RunAB(out _));
                    sb.AppendLine();
                    sb.Append(SimAtScale(opts, seed));
                    File.WriteAllText("RESULTS.md", sb.ToString());
                    Console.WriteLine("\nwrote RESULTS.md");
                    return rc;
                }
                default:
                    Console.WriteLine("usage: harness [verify|bench|herding|sim|all] [--key value ...]");
                    return 2;
            }
        }

        private static string Header()
            => $"# CS2 Trip Simulation Rebuild — Harness Results\n\nGenerated by `CS2Path.Harness` on {Environment.OSVersion.Platform}, {Environment.ProcessorCount} cores, .NET {Environment.Version}.\n\n";

        private static Dictionary<string, string> ParseOpts(string[] args)
        {
            var d = new Dictionary<string, string>();
            for (int i = 1; i < args.Length - 1; i++)
                if (args[i].StartsWith("--")) d[args[i].Substring(2)] = args[i + 1];
            return d;
        }

        private static long GetOpt(Dictionary<string, string> o, string k, long dflt)
            => o.TryGetValue(k, out var v) ? long.Parse(v) : dflt;

        private static double Pct(List<double> xs, double p)
        {
            if (xs.Count == 0) return double.NaN;
            var s = xs.OrderBy(x => x).ToList();
            int i = Math.Min(s.Count - 1, (int)(p * s.Count));
            return s[i];
        }

        // ==================================================================
        private static string Bench(Dictionary<string, string> opts, ulong seed)
        {
            int cols = (int)GetOpt(opts, "cols", 362), rows = (int)GetOpt(opts, "rows", 362);
            int profiles = (int)GetOpt(opts, "profiles", 8);
            int nQueries = (int)GetOpt(opts, "queries", 100_000);
            int nTrips = (int)GetOpt(opts, "trips", 20_000);
            var sb = new StringBuilder();
            var sw = Stopwatch.StartNew();

            Console.WriteLine($"bench: building synthetic city {cols}x{rows}...");
            var city = SyntheticCity.Build(cols, rows, 50_000, 10_000, seed);
            var g = city.G;
            Console.WriteLine($"  nodes={g.NodeCount:N0} edges={g.EdgeCount:N0}");
            var anchors = city.BuildAnchors(profiles);
            int K = anchors.MetricCount;

            Console.WriteLine($"bench: Layer 0/1 build (K={K} metrics)...");
            var eng = RoutingEngine.Build(g, anchors);
            long weightBytes = (long)eng.Skeleton.ArcCount * K * 4 * 2;
            Console.WriteLine($"  order={eng.BuildOrderMs:0}ms skeleton={eng.BuildSkeletonMs:0}ms customize={eng.FullCustomizeMs:0.0}ms arcs={eng.Skeleton.ArcCount:N0} height={eng.Skeleton.TreeHeight}");

            sb.AppendLine("## Scale benchmark (plan §6 targets)");
            sb.AppendLine();
            sb.AppendLine($"Graph: **{g.NodeCount:N0} nodes / {g.EdgeCount:N0} directed lane-edges** (three road tiers, holes). Anchor grid: **{profiles} preference profiles × 2 scenarios = {K} metrics**.");
            sb.AppendLine();
            sb.AppendLine("### Layer 0 — structure (once per topology edit, async)");
            sb.AppendLine();
            sb.AppendLine("| stage | result |");
            sb.AppendLine("|---|---|");
            sb.AppendLine($"| nested dissection order | {eng.BuildOrderMs:N0} ms |");
            sb.AppendLine($"| contraction (all shortcuts) | {eng.BuildSkeletonMs:N0} ms |");
            sb.AppendLine($"| chordal arcs | {eng.Skeleton.ArcCount:N0} ({(double)eng.Skeleton.ArcCount / (g.EdgeCount / 2):0.0}x undirected edges) |");
            sb.AppendLine($"| elimination tree height | {eng.Skeleton.TreeHeight} |");
            sb.AppendLine($"| multi-metric weight memory | {weightBytes / 1e6:N0} MB ({K} metrics, fwd+bwd) |");
            sb.AppendLine();

            // --- customization ---
            Console.WriteLine("bench: full + partial customization...");
            var rng = new SplitMix64(seed + 100);
            sw.Restart();
            eng.Metrics.ResetAll();
            eng.Metrics.FullCustomize();
            double fullMs = sw.Elapsed.TotalMilliseconds;

            var changed = new List<int>();
            var partial100 = new List<double>(); var partial1000 = new List<double>();
            long arcs100 = 0, arcs1000 = 0;
            for (int round = 0; round < 30; round++)
            {
                foreach (var (list, count) in new[] { (partial100, 100), (partial1000, 1000) })
                {
                    changed.Clear();
                    for (int i = 0; i < count; i++)
                    {
                        int e = rng.NextInt(g.EdgeCount);
                        g.TimeLive[e] = g.TimeFree[e] * (0.8f + 1.6f * rng.NextFloat());
                        changed.Add(e);
                    }
                    sw.Restart();
                    eng.RefreshLive(changed);
                    list.Add(sw.Elapsed.TotalMilliseconds);
                    if (count == 100) arcs100 += eng.Metrics.LastPartialArcsRecomputed;
                    else arcs1000 += eng.Metrics.LastPartialArcsRecomputed;
                }
            }
            sb.AppendLine("### Layer 1 — customization (per traffic refresh)");
            sb.AppendLine();
            sb.AppendLine("| operation | time | §6 target |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine($"| full customization, all {K} metrics | {fullMs:N0} ms | < 10 ms (Burst/SIMD budget) |");
            sb.AppendLine($"| partial, 100 changed edges (live lanes) | median {Pct(partial100, 0.5):0.00} ms, p99 {Pct(partial100, 0.99):0.00} ms ({arcs100 / 30:N0} arcs) | < 1 ms |");
            sb.AppendLine($"| partial, 1000 changed edges (live lanes) | median {Pct(partial1000, 0.5):0.00} ms, p99 {Pct(partial1000, 0.99):0.00} ms ({arcs1000 / 30:N0} arcs) | — |");
            sb.AppendLine();

            // --- queries ---
            Console.WriteLine($"bench: {nQueries:N0} point-to-point queries (4 threads)...");
            int liveStart = anchors.ScenarioBlockStart(CS2Path.Core.Scenario.Live);
            var pairs = new (int s, int t, int k)[nQueries];
            for (int i = 0; i < nQueries; i++)
                pairs[i] = (rng.NextInt(g.NodeCount), rng.NextInt(g.NodeCount), liveStart + rng.NextInt(profiles));
            // warmup
            {
                var wctx = eng.Query.CreateContext();
                for (int i = 0; i < 2000; i++) eng.Query.Distance(wctx, pairs[i].s, pairs[i].t, pairs[i].k);
            }
            int nThreads = Math.Min(4, Environment.ProcessorCount);
            var lat = new List<double>[nThreads];
            sw.Restart();
            Parallel.For(0, nThreads, th =>
            {
                var ctx = eng.Query.CreateContext();
                var mine = new List<double>(nQueries / nThreads + 1);
                for (int i = th; i < nQueries; i += nThreads)
                {
                    long t0 = Stopwatch.GetTimestamp();
                    eng.Query.Distance(ctx, pairs[i].s, pairs[i].t, pairs[i].k);
                    mine.Add((Stopwatch.GetTimestamp() - t0) * 1e6 / Stopwatch.Frequency);
                }
                lat[th] = mine;
            });
            double wallS = sw.Elapsed.TotalSeconds;
            var allLat = lat.SelectMany(x => x).ToList();

            // spot correctness at scale
            int bad = 0;
            {
                var ctx = eng.Query.CreateContext();
                for (int i = 0; i < 300; i++)
                {
                    var (s, t, k) = pairs[i];
                    float dc = eng.Query.Distance(ctx, s, t, k);
                    float dr = Reference.Dijkstra(g, s, t, e => anchors.EdgeWeight(g, e, k));
                    bool close = float.IsPositiveInfinity(dc) && float.IsPositiveInfinity(dr)
                                 || Math.Abs(dc - dr) <= 1e-3f * Math.Max(1f, Math.Max(dc, dr));
                    if (!close) bad++;
                }
            }

            // vanilla-style Dijkstra cost on the same graph
            Console.WriteLine("bench: reference Dijkstra timing (the vanilla per-query cost)...");
            var djLat = new List<double>();
            for (int i = 0; i < 150; i++)
            {
                var (s, t, k) = pairs[i];
                long t0 = Stopwatch.GetTimestamp();
                Reference.Dijkstra(g, s, t, e => anchors.EdgeWeight(g, e, k));
                djLat.Add((Stopwatch.GetTimestamp() - t0) * 1e6 / Stopwatch.Frequency);
            }

            sb.AppendLine("### Layer 2 — point-to-point queries (per trip, live metric)");
            sb.AppendLine();
            sb.AppendLine("| measure | CCH (this mod) | reference Dijkstra (vanilla-style) |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine($"| median latency | {Pct(allLat, 0.5):0.0} µs | {Pct(djLat, 0.5):N0} µs |");
            sb.AppendLine($"| mean latency | {allLat.Average():0.0} µs | {djLat.Average():N0} µs |");
            sb.AppendLine($"| p99 latency | {Pct(allLat, 0.99):0.0} µs | {Pct(djLat, 0.99):N0} µs |");
            sb.AppendLine($"| throughput ({nThreads} threads) | {nQueries / wallS:N0} queries/s | — |");
            sb.AppendLine($"| correctness spot-check | {300 - bad}/300 exact | (reference) |");
            sb.AppendLine();
            sb.AppendLine($"**Speedup: {djLat.Average() / allLat.Average():N0}x per query** (plan §2 asks ~3 orders of magnitude; §6 target p99 < 20 µs).");
            sb.AppendLine();
            Console.WriteLine($"  CCH mean={allLat.Average():0.0}us p99={Pct(allLat, 0.99):0.0}us | Dijkstra mean={djLat.Average():N0}us | correct {300 - bad}/300");

            // --- portfolios ---
            Console.WriteLine($"bench: {nTrips:N0} full trip plans (portfolio + certificate), {nThreads} threads...");
            var trips = new TripRequest[nTrips];
            for (int i = 0; i < nTrips; i++)
            {
                int s = rng.NextInt(g.NodeCount), t = rng.NextInt(g.NodeCount);
                trips[i] = new TripRequest
                {
                    AgentId = i, Origin = s, Destination = t,
                    Alpha = city.Citizens[rng.NextInt(city.Citizens.Length)],
                    Seed = seed ^ (ulong)(i * 6364136223846793005L),
                    LongOrTransit = i % 8 == 0,
                };
            }
            var telemetry = new Telemetry();
            var planLat = new List<double>[nThreads];
            var altCounts = new List<double>[nThreads];
            sw.Restart();
            Parallel.For(0, nThreads, th =>
            {
                var planner = new TripPlanner(eng.Metrics, eng.Query);
                planner.Stats.RepairTimesUs = new List<double>();
                var mine = new List<double>(nTrips / nThreads + 1);
                var alts = new List<double>(nTrips / nThreads + 1);
                for (int i = th; i < nTrips; i += nThreads)
                {
                    long t0 = Stopwatch.GetTimestamp();
                    var plan = planner.PlanFixed(in trips[i]);
                    mine.Add((Stopwatch.GetTimestamp() - t0) * 1e6 / Stopwatch.Frequency);
                    if (plan.HasPlan) alts.Add(plan.Alts.Count);
                }
                lock (telemetry) telemetry.AddFrom(planner.Stats);
                planLat[th] = mine; altCounts[th] = alts;
            });
            double planWallS = sw.Elapsed.TotalSeconds;
            var allPlan = planLat.SelectMany(x => x).ToList();
            var allAlts = altCounts.SelectMany(x => x).ToList();
            double certFrac = (double)telemetry.CertifiedTrips / Math.Max(1, telemetry.TripsPlanned);
            long uncert = telemetry.TripsPlanned - telemetry.CertifiedTrips;
            double meanGap = telemetry.CertGapSum / Math.Max(1, uncert + telemetry.RepairSearches);
            var repairs = telemetry.RepairTimesUs ?? new List<double>();

            sb.AppendLine("### Layer 2 — full trip planning (portfolio + choice + certificate)");
            sb.AppendLine();
            sb.AppendLine("| measure | value | §6 target |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine($"| plan latency median / p99 | {Pct(allPlan, 0.5):0.0} µs / {Pct(allPlan, 0.99):N0} µs | — |");
            sb.AppendLine($"| planning throughput ({nThreads} threads) | {nTrips / planWallS:N0} trips/s | — |");
            sb.AppendLine($"| mean portfolio size | {allAlts.DefaultIfEmpty(0).Average():0.0} alternatives | 3-5 |");
            sb.AppendLine($"| certified-exact fraction | {certFrac:P1} | ≥ 90% |");
            sb.AppendLine($"| mean certified gap (uncertified tail) | {meanGap:P2} | < 1% |");
            sb.AppendLine($"| repair searches | {telemetry.RepairSearches:N0} ({(double)telemetry.RepairSearches / Math.Max(1, telemetry.TripsPlanned):P1} of trips) | 2-10% |");
            sb.AppendLine($"| repair p99 latency | {Pct(repairs, 0.99):N0} µs | < 500 µs |");
            sb.AppendLine($"| Suurballe backups | {telemetry.DisjointBackups:N0} | — |");
            sb.AppendLine($"| unreachable trips | {telemetry.UnreachableTrips:N0} | no increase vs vanilla (= genuine) |");
            sb.AppendLine();
            Console.WriteLine($"  plan median={Pct(allPlan, 0.5):0.0}us certified={certFrac:P1} repairs={telemetry.RepairSearches} repairP99={Pct(repairs, 0.99):N0}us");

            // --- re-pricing ---
            Console.WriteLine("bench: via-node re-pricing...");
            {
                var planner = new TripPlanner(eng.Metrics, eng.Query);
                var plans = new List<TripPlan>();
                for (int i = 0; i < 300; i++)
                {
                    var p = planner.PlanFixed(in trips[i]);
                    if (p.HasPlan) plans.Add(p);
                }
                var repLat = new List<double>(20000);
                for (int i = 0; i < 20000; i++)
                {
                    var p = plans[i % plans.Count];
                    var alt = p.Alts[i % p.Alts.Count];
                    long t0 = Stopwatch.GetTimestamp();
                    planner.RepriceAlternative(p.Origin, in alt, p.NearestProfile);
                    repLat.Add((Stopwatch.GetTimestamp() - t0) * 1e6 / Stopwatch.Frequency);
                }
                sb.AppendLine("### Layer 4 — via-node re-pricing (per alternative, two CCH queries)");
                sb.AppendLine();
                sb.AppendLine($"median {Pct(repLat, 0.5):0.0} µs, p99 {Pct(repLat, 0.99):0.0} µs — a 5-alternative portfolio re-prices in ~{5 * Pct(repLat, 0.5):0} µs.");
                sb.AppendLine();
            }

            // --- Layer 3 buckets + dispatch ---
            Console.WriteLine("bench: destination buckets + dispatch...");
            {
                var ctx = eng.Query.CreateContext();
                int refMetric = anchors.MetricIndex(0, CS2Path.Core.Scenario.Live);
                sw.Restart();
                var buckets = DestinationBuckets.Build(eng.Query, ctx, city.Dests, refMetric);
                double buildMs = sw.Elapsed.TotalMilliseconds;
                sw.Restart();
                buckets.RefreshSlice(ctx, 500);
                double sliceMs = sw.Elapsed.TotalMilliseconds;

                var buf = new DestinationCandidate[8];
                var scanLat = new List<double>(10000);
                long entries = 0;
                for (int i = 0; i < 10000; i++)
                {
                    int s = rng.NextInt(g.NodeCount);
                    int cat = rng.NextInt(city.Dests.CategoryCount);
                    long t0 = Stopwatch.GetTimestamp();
                    buckets.Scan(ctx, s, cat, buf, 6);
                    scanLat.Add((Stopwatch.GetTimestamp() - t0) * 1e6 / Stopwatch.Frequency);
                    entries += buckets.LastScanEntries;
                }

                var fleet = FleetIndex.Create(eng.Query, 200, refMetric);
                for (int v = 0; v < 200; v++) fleet.PostVehicle(ctx, v, rng.NextInt(g.NodeCount));
                var dispLat = new List<double>(10000);
                for (int i = 0; i < 10000; i++)
                {
                    long t0 = Stopwatch.GetTimestamp();
                    fleet.Dispatch(ctx, rng.NextInt(g.NodeCount));
                    dispLat.Add((Stopwatch.GetTimestamp() - t0) * 1e6 / Stopwatch.Frequency);
                }

                sb.AppendLine("### Layer 3 — flexible destinations + service dispatch");
                sb.AppendLine();
                sb.AppendLine("| measure | value |");
                sb.AppendLine("|---|---|");
                sb.AppendLine($"| bucket build, {city.Dests.Count:N0} destinations | {buildMs:N0} ms ({buckets.EntriesTotal:N0} entries) |");
                sb.AppendLine($"| staggered refresh, 500 backward searches | {sliceMs:0.0} ms |");
                sb.AppendLine($"| shopper query (scan {city.Dests.Count / city.Dests.CategoryCount:N0} dests/category) | median {Pct(scanLat, 0.5):0.0} µs, p99 {Pct(scanLat, 0.99):N0} µs, {entries / 10000} entries scanned |");
                sb.AppendLine($"| dispatch query (fleet of 200) | median {Pct(dispLat, 0.5):0.0} µs, p99 {Pct(dispLat, 0.99):N0} µs |");
                sb.AppendLine();
                Console.WriteLine($"  buckets build={buildMs:N0}ms scan median={Pct(scanLat, 0.5):0.0}us dispatch median={Pct(dispLat, 0.5):0.0}us");
            }

            sb.AppendLine($"Process memory after benchmark: {GC.GetTotalMemory(false) / 1e6:N0} MB managed.");
            sb.AppendLine();
            return sb.ToString();
        }

        // ==================================================================
        private static string SimAtScale(Dictionary<string, string> opts, ulong seed)
        {
            int cols = (int)GetOpt(opts, "cols", 362), rows = (int)GetOpt(opts, "rows", 362);
            int nTrips = (int)GetOpt(opts, "trips", 100_000);
            int ticks = (int)GetOpt(opts, "ticks", 1500);
            int profiles = (int)GetOpt(opts, "profiles", 8);
            var sb = new StringBuilder();

            Console.WriteLine($"sim: integrated simulation, {nTrips:N0} trips over {ticks} ticks...");
            var city = SyntheticCity.Build(cols, rows, 50_000, 5_000, seed);
            var anchors = city.BuildAnchors(profiles);
            var eng = RoutingEngine.Build(city.G, anchors);
            var sim = TrafficSim.Create(city.G, city.JamCapacity, SimMode.Rebuild, eng);
            var rng = new SplitMix64(seed + 7);
            int n = city.G.NodeCount;
            int departWindow = (int)(ticks * 0.6);
            for (int i = 0; i < nTrips; i++)
            {
                sim.AddTrip(1 + rng.NextInt(departWindow), new TripRequest
                {
                    AgentId = i, Origin = rng.NextInt(n), Destination = rng.NextInt(n),
                    Alpha = city.Citizens[rng.NextInt(city.Citizens.Length)],
                    Seed = seed ^ (ulong)(i * 2862933555777941757L),
                    LongOrTransit = i % 10 == 0,
                });
            }
            var sw = Stopwatch.StartNew();
            int lastReport = 0;
            sim.Run(ticks, tick =>
            {
                if (tick - lastReport >= 250)
                {
                    lastReport = tick;
                    Console.WriteLine($"  tick {tick}: active={CountActive(sim)} arrived={sim.FinishedTrips} softClosed={sim.Detector!.SoftClosedCount} switches={sim.Upd!.Stats.Switches}");
                }
            });
            double wallS = sw.Elapsed.TotalSeconds;
            var ps = sim.Planner!.Stats;
            var us = sim.Upd!.Stats;
            double simSecondsPerTick = 4.0; // Dt
            double realtimeFactor = ticks * simSecondsPerTick / wallS;

            sb.AppendLine("## Integrated simulation at scale");
            sb.AppendLine();
            sb.AppendLine($"{city.G.NodeCount:N0}-node city, {nTrips:N0} trips, {ticks} ticks of {simSecondsPerTick}s (~{ticks * simSecondsPerTick / 3600:0.0} sim-hours), single-threaded harness on {Environment.ProcessorCount} cores.");
            sb.AppendLine();
            sb.AppendLine("| measure | value |");
            sb.AppendLine("|---|---|");
            sb.AppendLine($"| wall time | {wallS:N0} s ({realtimeFactor:0.0}x realtime) |");
            sb.AppendLine($"| arrivals | {sim.FinishedTrips:N0} / {sim.Trips.Count:N0} |");
            sb.AppendLine($"| trips planned (incl. regenerations) | {ps.TripsPlanned:N0} |");
            sb.AppendLine($"| certified-exact fraction | {(double)ps.CertifiedTrips / Math.Max(1, ps.TripsPlanned):P1} |");
            sb.AppendLine($"| planning time | {sim.MsPlanning / 1000:0.0} s total, {sim.MsPlanning / Math.Max(1, ps.TripsPlanned) * 1000:N0} µs/trip |");
            sb.AppendLine($"| movement | {sim.MsMovement / ticks:0.00} ms/tick |");
            sb.AppendLine($"| live-metric partial customization | {sim.MsCustomize / (ticks / sim.RefreshInterval):0.00} ms/refresh |");
            sb.AppendLine($"| Layer-4 wakes + re-pricing | {sim.MsWakes / (ticks / sim.RefreshInterval):0.00} ms/refresh |");
            sb.AppendLine($"| re-prices / probes / regenerations | {us.Reprices:N0} / {us.Probes:N0} / {us.Regenerations:N0} |");
            sb.AppendLine($"| route switches (past hysteresis) | {us.Switches:N0} |");
            sb.AppendLine($"| event wakes (metered) / region wakes / sweeper | {us.EventWakes:N0} / {us.RegionWakes:N0} / {us.SweeperWakes:N0} |");
            sb.AppendLine($"| soft-closed edges at end | {sim.Detector!.SoftClosedCount:N0} |");
            sb.AppendLine($"| unreachable-trip events | {ps.UnreachableTrips:N0} |");
            sb.AppendLine();
            Console.WriteLine($"  done in {wallS:N0}s: arrived={sim.FinishedTrips}/{sim.Trips.Count} planned={ps.TripsPlanned} switches={us.Switches}");
            return sb.ToString();
        }

        private static int CountActive(TrafficSim sim)
        {
            int c = 0;
            foreach (var t in sim.Trips) if (!t.Finished) c++;
            return c;
        }
    }
}
